import "~/styles/globals.css"
import "@uploadthing/react/styles.css"

import { GeistSans } from "geist/font/sans"
import { type Metadata } from "next"
import { ClerkProvider } from "@clerk/nextjs"
import Nav from "./_components/Nav"

export const metadata: Metadata = {
  title: "Next Gallery",
  description: "Generated by Igor Almeida",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${GeistSans.variable}`}
      >
        <body className="font-sans bg-black text-white">
          <div className="h-screen flex flex-col">
            <Nav></Nav>
            <main className="overflow-y-scroll min-h-screen">{children}</main>
          </div>
          {modal}
          <div id="modal-root"></div>
        </body>
      </html>
    </ClerkProvider>
  )
}
