import "~/styles/globals.css"

import { GeistSans } from "geist/font/sans"
import { type Metadata } from "next"
import { ClerkProvider } from "@clerk/nextjs"
import Nav from "./_components/Nav"

export const metadata: Metadata = {
  title: "Next Gallery",
  description: "Generated by Igor Almeida",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${GeistSans.variable}`}
      >
        <body className="font-sans bg-black flex flex-col gap-4">
          <Nav></Nav>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
